# Generated by Django 5.2.12 on 2026-03-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_seed_music_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
